# Generated by Django 6.0.6 on 2026-06-25 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=40, help_text='Maximum student seating capacity'),
        ),
        migrations.AddField(
            model_name='room',
            name='class_type',
            field=models.CharField(choices=[('Theory', 'Theory'), ('Lab', 'Lab')], default='Theory', max_length=15),
        ),
        migrations.AddField(
            model_name='room',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routines.faculty'),
        ),
        migrations.AddField(
            model_name='room',
            name='floor_no',
            field=models.CharField(default='1st Floor', max_length=20),
        ),
    ]
