# Generated by Django 6.0.6 on 2026-06-27 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='class_type',
            field=models.CharField(choices=[('Theory', 'Theory'), ('Lab', 'Lab')], default='Theory', max_length=10),
        ),
        migrations.AddField(
            model_name='routine',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='routine',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routines.room'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='section',
            field=models.CharField(blank=True, help_text='e.g., A1, B2 (Only for Lab)', max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
